// Code generated by "stringer -type=Type"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeNil-1]
	_ = x[TypeBoolean-2]
	_ = x[TypeNumber-3]
	_ = x[TypeString-4]
	_ = x[TypeFunction-5]
	_ = x[TypeUserdata-6]
	_ = x[TypeThread-7]
	_ = x[TypeTable-8]
}

const _Type_name = "TypeInvalidTypeNilTypeBooleanTypeNumberTypeStringTypeFunctionTypeUserdataTypeThreadTypeTable"

var _Type_index = [...]uint8{0, 11, 18, 29, 39, 49, 61, 73, 83, 92}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
