name: Build
on:
  push:
  pull_request:
jobs:

  build:
    name: Build for OS ${{ matrix.goos }} with ARCH ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ 1.14 ]
        goos: [ darwin, linux, windows ]
        goarch: [ 386, amd64 ]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: windows
            goarch: 386
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go
      - uses: actions/checkout@v1
      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/lua -ldflags="-s -w -X 'main.TheVersion=${GITHUB_REF}'" ./cmd/lua
      - uses: actions-github/upx@master
        with:
          dir: ./bin
          upx_args: '--ultra-brute'
      - uses: actions/upload-artifact@master
        with:
          name: binaries_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./bin
      - name: Create issue if failure
        if: ${{ success() }} # for testing
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://crushit.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_DESCRIPTION: |
            It seems like $GITHUB_WORKFLOW has failed.
            Commit: $GITHUB_SHA
            $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          JIRA_ISSUE_SUMMARY: $GITHUB_WORKFLOW failure
          JIRA_ISSUE_TYPE: Bug
          JIRA_PROJECT: Lua
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}