name: Build
on:
  push:
  pull_request:
jobs:

  build:
    name: Build for OS ${{ matrix.goos }} with ARCH ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ 1.14 ]
        goos: [ darwin, linux, windows ]
        goarch: [ 386, amd64 ]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: windows
            goarch: 386
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go
      - uses: actions/checkout@v1
      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/lua -ldflags="-s -w -X 'main.TheVersion=${GITHUB_REF}'" ./cmd/lua
      - uses: actions-github/upx@master
        with:
          dir: ./bin
          upx_args: '--ultra-brute'
      - uses: actions/upload-artifact@master
        with:
          name: binaries_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./bin
      - name: Login to Jira
        uses: atlassian/gajira-login@master
        if: success()
        env:
          JIRA_BASE_URL: https://crushit.atlassian.net
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create Jira issue on job failure
        uses: atlassian/gajira-create@master
        if: success()
        with:
          project: LUA
          issuetype: Bug
          summary: ${{ github.workflow }} ${{ github.action }} failed for ${{ github.repository }}
          description: |
            It seems like https://github.com/${{ github.repository }}/actions/run/${{ github.run_id }} failed.
            Commit: ${{ github.sha }}